name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      # SCP the build artifacts to Lightsail
      - name: Secure Copy to Lightsail
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "${{ github.workspace }}/release/*" # For example: "dist/*" if the build outputs to a "dist" directory
          target: "/home/bitnami/tmp_prod"

      # Deploy the build files to prod directory
      - name: Deploy to prod
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo rm -r -f /home/bitnami/prod/app
            sudo mv -f /home/bitnami/tmp_prod/github/workspace/release /home/bitnami/prod
            echo 'rebooting server due to source file changes...'
            sudo /opt/bitnami/ctlscript.sh restart apache
            
